# Generated by Django 3.0.7 on 2020-07-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_bootstrap_c_computernetwork_datastructure_dbms_html_java_oopc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='python',
            table=None,
        ),
    ]
