from django.contrib import admin
from django.urls import path
from QuizApp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index1', views.h, name='index1'),
#First Nav-bar
    path('register', views.registerUser, name='register'),
    path('login', views.loginUser, name='login'),
    path('logout', views.logoutUser, name='logout'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('blog', views.blog, name='Blog'),
    path('privacyPolicy', views.privacyPolicy, name='PrivacyPolicy'),
    path('tremsConditions', views.tremsConditions, name='TremsConditions'),
#Home page
    path('python', views.python, name='python-quiz'),
    path('java', views.java, name='java-quiz'),
    path('oopc', views.oopc, name='c++-quiz'),
    path('c', views.c, name='c-quiz'),
    path('dbms', views.dbms, name='dbms-quiz'),
    path('html', views.html, name='html-quiz'),
    path('network', views.network, name='network-quiz'),
    path('bootstrap', views.bootstrap, name='bootstrap-quiz'),
    path('datastructure', views.datastructure, name='datastructure-quiz'),
# second nav-bar
    path('gk', views.GK, name="gk"),
    path('aptitude', views.aptitude, name="Aptitude"),
    path('logical', views.logical, name="Logical"),
    path('current_affair', views.current_affair, name="Current_affairs"),
    path('science', views.science, name="science"),
    path('interview', views.interview, name="Interview"),
    path('online_test', views.online_test, name="Online_test"),
    path('varbal', views.varbal, name="Varbal"),
    path('engineering', views.engineering, name="Engineering"),
    path('search',views.search, name='search'),
# GK urls 
    path('basicGK',views.basicGK, name='BasicGK'),
    path('technology',views.technology, name='Technology'),
    path('indianHistory',views.indianHistory, name='IndianHistory'),
    path('honoursAward',views.honoursAward, name='HonoursAward'),
    path('generalScience',views.generalScience, name='GeneralScience'),
    path('bookAuthor',views.bookAuthor, name='BookAuthor'),
    path('famousPersonalities',views.famousPersonalities, name='FamousPersonalities'),
    path('indianCulture',views.indianCulture, name='IndianCulture'), 
    path('indianPolitics',views.indianPolitics, name='IndianPolitics'),
    path('sports',views.sports, name='Sports'),
    path('worldGeography',views.worldGeography, name='WorldGeography'),
    path('worldOrganisations',views.worldOrganisations, name='WorldOrganisations'),
    path('indianEconomy',views.indianEconomy, name='IndianEconomy'),
    path('indianGeography',views.indianGeography, name='IndianGeography'),
    path('inventions',views.inventions, name='Inventions'),
    path('famousPlaceIndia',views.famousPlaceIndia, name='FamousPlaceIndia'),
# Aptitude urls
    path('problemTrains',views.problemTrains, name='ProblemTrains'),
    path('permutationCombination',views.permutationCombination, name='PermutationCombination'),
    path('timeDistance',views.timeDistance, name='TimeDistance'),
    path('hCFAndLCM',views.hCFAndLCM, name='HCFAndLCM'),
    path('simpleInterest',views.simpleInterest, name='SimpleInterest'),
    path('decimalFraction',views.decimalFraction, name='decimalFraction'),
    path('compoundInterest',views.compoundInterest, name='CompoundInterest'),
    path('squareCubeRoot',views.squareCubeRoot, name='SquareCubeRoot'),
    path('profitLoss',views.profitLoss, name='ProfitLoss'),
    path('simplification',views.simplification, name='Simplification'),
    path('partnership',views.partnership, name='Partnership'),
    path('ratioProportion',views.ratioProportion, name='RatioProportion'),
    path('problemAge',views.problemAge, name='ProblemAge'),
    path('pipesCistern',views.pipesCistern, name='PipesCistern'),
    path('volumeSurfaceArea',views.volumeSurfaceArea, name='VolumeSurfaceArea'),
    path('racesGame',views.racesGame, name='RacesGame'),
#Logical Urls
    path('numberSeries',views.numberSeries, name='NumberSeries'),
    path('statementAssumption',views.statementAssumption, name='StatementAssumption'),
    path('letterSymbol',views.letterSymbol, name='LetterSymbol'),
    path('courceAction',views.courceAction, name='CourceAction'),
    path('verbalClassification',views.verbalClassification, name='VerbalClassification'),
    path('statementConClusion',views.statementConClusion, name='StatementConClusion'),
    path('artificial',views.artificial, name='Artificial'),
    path('themeDetection',views.themeDetection, name='ThemeDetection'),
    path('verbalReasoning',views.verbalReasoning, name='VerbalReasoning'),
    path('causeEffect',views.causeEffect, name='CauseEffect'),
    path('logicalProblem',views.logicalProblem, name='LogicalProblem'),
    path('statementArgument',views.statementArgument, name='StatementArgument'),
    path('logicalGame',views.logicalGame, name='LogicalGame'),
    path('logicalDeduction',views.logicalDeduction, name='LogicalDeduction'),
    path('analyzingArgument',views.analyzingArgument, name='AnalyzingArgument'),
    path('essentialPart',views.essentialPart, name='EssentialPart'),
#Current-Affairs Urls
    path('state',views.state, name='State'),
    path('awardHonour',views.awardHonour, name='AwardHonour'),
    path('politics',views.politics, name='Politics'),
    path('banking',views.banking, name='Banking'),
    path('national',views.national, name='National'),
    path('billsActs',views.billsActs, name='BillsActs'),
    path('persons',views.persons, name='Persons'),
    path('business',views.business, name='Business'),
    path('international',views.international, name='International'),
    path('defence',views.defence, name='Defence'),
    path('ImportantDay',views.ImportantDay, name='ImportantDay'),
    path('economy',views.economy, name='Economy'),
    path('agriculture',views.agriculture, name='Agriculture'),
    path('education',views.education, name='Education'),
    path('artCulture',views.artCulture, name='ArtCulture'),
    path('environment',views.environment, name='Environment'),
#Science urls
    path('BasicScience',views.BasicScience, name='BasicScience'),
    path('kinematics',views.kinematics, name='Kinematics'),
    path('physics',views.physics, name='physics'),
    path('electrostatics',views.electrostatics, name='Electrostatics'),
    path('chemistry',views.chemistry, name='Chemistry'),
    path('organicChemistry',views.organicChemistry, name='OrganicChemistry'),
    path('biology',views.biology, name='Biology'),
    path('chemicalThermodynamics',views.chemicalThermodynamics, name='ChemicalThermodynamics'),
    path('mathematics',views.mathematics, name='Mathematics'),
    path('chemicalKinetics',views.chemicalKinetics, name='ChemicalKinetics'),
    path('english',views.english, name='English'),
    path('plantPhysiology',views.plantPhysiology, name='PlantPhysiology'),
    path('thermodynamics',views.thermodynamics, name='thermodynamics'),
    path('humanPhysiology',views.humanPhysiology, name='HumanPhysiology'),
    path('electromagneticWaves',views.electromagneticWaves, name='ElectromagneticWaves'),
    path('biotechnologyApplication',views.biotechnologyApplication, name='BiotechnologyApplication'),
#InterView Urls
    path('placementPapers',views.placementPapers, name='PlacementPapers'),
    path('hRInterview',views.hRInterview, name='HRInterview'),
    path('technicalInterview',views.technicalInterview, name='TechnicalInterview'),
    path('groupDisCussion',views.groupDisCussion, name='GroupDisCussion'),
    path('submitYourPlacement',views.submitYourPlacement, name='SubmitYourPlacement'),
    path('bodyLanguage',views.bodyLanguage, name='BodyLanguage'),
#Online Test Urls
    path('aptitudeTest',views.aptitudeTest, name='AptitudeTest'),
    path('biotechnologyTest',views.biotechnologyTest, name='BiotechnologyTest'),
    path('verbalAbilityTest',views.verbalAbilityTest, name='VerbalAbilityTest'),
    path('biochemicalEngineering',views.biochemicalEngineering, name='BiochemicalEngineering'),
    path('logicalReasoning',views.logicalReasoning, name='LogicalReasoning'),
    path('digitalElectronics',views.digitalElectronics, name='DigitalElectronics'),
    path('nonVerbalReasoning',views.nonVerbalReasoning, name='NonVerbalReasoning'),
    path('electronics',views.electronics, name='Electronics'),
    path('dataInterpretation',views.dataInterpretation, name='DataInterpretation'),
    path('chemicalEngineering',views.chemicalEngineering, name='ChemicalEngineering'),
    path('generalKnowledge',views.generalKnowledge, name='GeneralKnowledge'),
    path('networkingTest',views.networkingTest, name='NetworkingTest'),
    path('currentAffairsTest',views.currentAffairsTest, name='CurrentAffairsTest'),
    path('computerScienceTest',views.computerScienceTest, name='ComputerScienceTest'),
    path('microbiologyTest',views.microbiologyTest, name='MicrobiologyTest'),
    path('c_ShapProgramming',views.c_ShapProgramming, name='C_ShapProgramming'),
#Varbal Urls
    path('spottingError',views.spottingError, name='SpottingError'),
    path('sentenceImprovement',views.sentenceImprovement, name='SentenceImprovement'),
    path('synonyms',views.synonyms, name='synonyms'),
    path('completingStatement',views.completingStatement, name='CompletingStatement'),
    path('antonyms',views.antonyms, name='Antonyms'),
    path('orderingSentences',views.orderingSentences, name='OrderingSentences'),
    path('selectingWord',views.selectingWord, name='SelectingWord'),
    path('paragraphFormation',views.paragraphFormation, name='ParagraphFormation'),
    path('spelling',views.spelling, name='Spelling'),
    path('clostTest',views.clostTest, name='ClostTest'),
    path('sentenceFormation',views.sentenceFormation, name='SentenceFormation'),
    path('comprehension',views.comprehension, name='Comprehension'),
    path('orderingWord',views.orderingWord, name='OrderingWord'),
    path('oneWordSubstitutes',views.oneWordSubstitutes, name='OneWordSubstitutes'),
    path('sentenceCorrection',views.sentenceCorrection, name='SentenceCorrection'),
    path('idiomsPhrases',views.idiomsPhrases, name="IdiomsPhrases"),
#Engineering Urls
    path('computerScience',views.computerScience, name="CmputerScience"),
    path('chemical',views.chemical, name="chemical"),
    path('civil',views.civil, name="Civil"),
    path('mechanical',views.mechanical, name="Mechanical"),
    path('structural',views.structural, name="Structural"),
    path('electrical',views.electrical, name="Electrical"),
#

]